{
    "config": {
        "abort": {
            "already_configured": "Der Dienst ist bereits konfiguriert",
            "reauth_successful": "Die erneute Authentifizierung war erfolgreich"
        },
        "error": {
            "cannot_connect": "Verbindung fehlgeschlagen",
            "invalid_auth": "Ung\u00fcltige Authentifizierung"
        },
        "step": {
            "api_key": {
                "data": {
                    "api_key": "API-Schl\u00fcssel"
                }
            },
            "reauth_confirm": {
                "data": {
                    "api_key": "API-Schl\u00fcssel"
                },
                "description": "Bitte gib einen neuen API-Schl\u00fcssel f\u00fcr PI-Hole unter {host}/{location} ein",
                "title": "PI-Hole Integration erneut authentifizieren"
            },
            "user": {
                "data": {
                    "api_key": "API-Schl\u00fcssel",
                    "host": "Host",
                    "location": "Standort",
                    "name": "Name",
                    "port": "Port",
                    "ssl": "Verwendet ein SSL-Zertifikat",
                    "statistics_only": "Nur Statistiken",
                    "verify_ssl": "SSL-Zertifikat \u00fcberpr\u00fcfen"
                }
            }
        }
    },
    "issues": {
        "deprecated_yaml": {
            "description": "Die Konfiguration von PI-Hole mittels YAML wird entfernt.\n\nDeine bestehende YAML-Konfiguration wurde automatisch in die Benutzeroberfl\u00e4che importiert.\n\nEntferne die PI-Hole YAML-Konfiguration aus deiner configuration.yaml-Datei und starte den Home Assistant neu, um dieses Problem zu beheben.",
            "title": "Die PI-Hole YAML-Konfiguration wird entfernt"
        }
    }
}