{
    "config": {
        "abort": {
            "already_configured": "Il servizio \u00e8 gi\u00e0 configurato",
            "reauth_successful": "La nuova autenticazione \u00e8 stata eseguita correttamente"
        },
        "error": {
            "cannot_connect": "Impossibile connettersi",
            "invalid_auth": "Autenticazione non valida"
        },
        "step": {
            "api_key": {
                "data": {
                    "api_key": "Chiave API"
                }
            },
            "reauth_confirm": {
                "data": {
                    "api_key": "Chiave API"
                },
                "description": "Inserisci una nuova chiave API per PI-Hole in {host}/{location}",
                "title": "Autentica nuovamente l'integrazione PI-Hole"
            },
            "user": {
                "data": {
                    "api_key": "Chiave API",
                    "host": "Host",
                    "location": "Posizione",
                    "name": "Nome",
                    "port": "Porta",
                    "ssl": "Utilizza un certificato SSL",
                    "statistics_only": "Solo Statistiche",
                    "verify_ssl": "Verifica il certificato SSL"
                }
            }
        }
    },
    "issues": {
        "deprecated_yaml": {
            "description": "La configurazione di PI-Hole tramite YAML \u00e8 stata rimossa. \n\nLa configurazione YAML esistente \u00e8 stata importata automaticamente nell'interfaccia utente. \n\nRimuovi la configurazione YAML PI-Hole dal tuo file configuration.yaml e riavvia Home Assistant per risolvere questo problema.",
            "title": "La configurazione YAML PI-Hole \u00e8 in fase di rimozione"
        }
    }
}